#FROM rust:latest
FROM rustlang/rust:nightly

COPY . /src
WORKDIR /src

RUN apt-get update && apt-get install -y musl-tools musl-dev

#RUN cargo install xargo
#RUN rustup toolchain install nightly-x86_64-unknown-linux-musl
#RUN rustup default nightly-x86_64-unknown-linux-musl
RUN rustup override add nightly
RUN rustup target add x86_64-unknown-linux-musl
RUN rustup target add --toolchain=nightly x86_64-unknown-linux-musl
RUN rustup component add --toolchain=nightly --target=x86_64-unknown-linux-musl rust-src
RUN ./xargo install --target=x86_64-unknown-linux-musl --features bundled --path . --root /
RUN strip /bin/shaft

FROM scratch

WORKDIR /root/
COPY --from=0 /bin/shaft shaft
COPY --from=0 /src/res/ res/

ENTRYPOINT ["./shaft"]
